services:
  price_watcher:
    image: gold-price-watcher:${TAG}
    build: ../.
    volumes:
      - ${DATA_FOLDER}:/price-watcher-data
    restart: unless-stopped
    networks:
      - "kafka-network"
networks:
  kafka-network:
    external: true
